### ISSUE TITLE
Mods not loading

### ISSUE THREAD

**Issue by HitByBricks** [dotaxis/7H-SteamDeck-Fix#11]
I successfully installed the app and downloaded mods (mainly the Satsuki ones). The game runs successfully (on my SD card) and the FFNx screen shows up but none of the mods are loaded.

**Comment by dotaxis** [comment]
You'll need to ask for help on the 7th Heaven Discord or open an issue on their Github: https://github.com/tsunamods-codes/7th-Heaven

All this script does is handle the installation process to get it running on Steam Deck, and you are already past that point.

**Comment by mattbell87** [comment]
I did notice that the script does fix mods not loading when you re-run it. I changed my Proton runtime to Proton-GE and noticed my mods were no longer appearing. All I had to do was run 7HFix.sh again and they loaded.

I wonder if its the Dinput.dll part of the script that fixes the issue.

**Comment by dotaxis** [comment]
> I wonder if its the Dinput.dll part of the script that fixes the issue.

This is correct.
