### ISSUE TITLE
SOrt of an issue with X vs Wayland

### ISSUE THREAD

**Issue by npaladin2000** [dotaxis/7H-SteamDeck-Fix#12]
I'm one of the ChimeraOS team members, and have been working on getting this working. Took a while to figure out, since we use GNOME rather than KDE, but as it turned out, while 7th Heaven wouldn't start under GNOME Wayand, it works fine under GNOME Xorg. Not sure if that's something you actually want to address but I thought I'd note it so no one else tears their hair out trying to figure it out.

**Comment by bosam** [comment]
From what I have been reading, Proton is not yet ready to support Wayland (Proton uses X11).
Until then, there is not a lot that can be done.

Ref: https://old.reddit.com/r/linux_gaming/comments/15ck6h1/will_steam_ever_go_native_wayland/

**Comment by npaladin2000** [comment]
Yeah, not surprising, we're using XWayland through Gamescope too. I guess SteamOS is using the Xorg version of KDE rather than the Wayland one though, which is probably what trips things up.

**Comment by dotaxis** [comment]
Not sure if the link will work, but somebody commented on my YouTube video saying they were able to get it to work on ChimeraOS with a "little fiddling." https://www.youtube.com/watch?v=6c2e6H1pzhg&lc=UgxuNE3INj_IdpeShY14AaABAg

That fiddling may just have been "don't use wayland" or it may have been something else. Have you experimented with GE-Proton?

**Comment by dotaxis** [comment]
Closing because we can't do anything about this.
