### ISSUE TITLE
Crashing when trying to run the game for the first time through 7th Heaven.

### ISSUE THREAD

**Issue by DanBaigo** [dotaxis/7H-SteamDeck-Fix#7]
Hi I followed the guide in the youtube video but for some reason when I try to launch the game when it gets to verifying game files the steam deck crashes after about 30 seconds and I can't get past this stage.

**Comment by shigutso** [comment]
Try forcing it to use Proton 7.0, that fixed for me

**Comment by dotaxis** [comment]
Have you launched vanilla FF7 on your steam deck at all? I think first run adds some files that are needed.

**Comment by perfectvirtual** [comment]
Having the same issue here, tried both launching vanilla once first (although I'm pretty sure I had already once), and launching 7th Heaven via Proton 7.0 (as well as 8.0 and experimental) - same result every time, crash or freeze after around 30 seconds. Could a Steam Deck update have messed something up from the previous working version?

**Comment by dotaxis** [comment]
I'm unable to reproduce this, so I'll need some more information to try and help.

SteamOS Version:
Proton Version:
FF7 Location (SD or Internal): 
Crash logs:

To get the crash logs, browse to the folder 7th Heaven is in and look under the "7thWorkshop/crashlogs" directory. You can get the location of 7th Heaven by examining the "Target" field in your Steam shortcut.

**Comment by DanBaigo** [comment]
No problems. Yeah I've just done a fresh install and followed the above advice and I'm still getting the same issue. Something is certainly not happy because the deck is cooking whilst sitting on the verifying game files stage. I tried Proton 7, GE etc all up to date versions. I've ran the game multiple times just to make sure.

SteamOS Version: 3.4.6
Proton Version: 7.0-6/GE-Proton8-3 
FF7 Location (SD or Internal): Tried both, currently on internal.
Crash logs:

I've had a look in the crash directory mentioned but there is nothing in there. I suspect this is because the app isn't actually crashing as such, its the deck itself crashing. Attached is a screenshot of what it looks like.
![PXL_20230530_181512492](https://github.com/dotaxis/7H-SteamDeck-Fix/assets/112517583/aa62fe45-bfe2-4501-9d0f-08f27997ee0c)

**Comment by dotaxis** [comment]
Can you verify the SHA1 checksum on your ff7.exe? Go into the directory 7th Heaven is in, then go up one folder and into the FF7 directory. The checksum should be 141822081b3f24ea70be35d59449e0ca098881e3

**Comment by DanBaigo** [comment]
I can confirm that is the check sum I am getting
![PXL_20230530_191537377 MP](https://github.com/dotaxis/7H-SteamDeck-Fix/assets/112517583/c8b61e94-76aa-4df4-8344-14afc10ae784)

**Comment by dotaxis** [comment]
Are you on a fresh install of FF7 as well as 7th Heaven?

I really don't know what might be causing this. I've tried a whole bunch of different things but have failed to make my system crash. 

Can you try launching with minimal validation? There's a dropdown next to the play button.

**Comment by DanBaigo** [comment]
Yes everything freshly reinstalled today. I'd uninstalled everything and started again incase I'd done something wrong.

Unfortunately cannot launch with minimal validation, same issue.

**Comment by dotaxis** [comment]
I doubt it will have any effect, but you could try the dev branch and see if the symlink makes a difference over copying the FF7 directory.

**Comment by DanBaigo** [comment]
So I installed the dev build from fresh, same issue. I took a copy of the console dump. Does this help? There is a permission error in there.
7thHeaven-v3.1.0.0_Release.exe not found. Downloading...
7thHeaven-v3.1.0.0_Release. 100%[=========================================>]  20.36M  7.09MB/s    in 2.9s

/home/deck/.local/share/Steam/steamapps/common/FINAL FANTASY VII
Finding APP_ID...
protontricks (WARNING): Protontricks does not appear to have access to the following directories:
 /run/media/mmcblk0p1

To fix this problem, grant access to the required directories by copying the following command and running it in a terminal:

flatpak override --user --filesystem=/run/media/mmcblk0p1 com.github.Matoking.protontricks

You will need to restart Protontricks for the settings to take effect.
protontricks (WARNING): Steam library folder /run/media/mmcblk0p1 not found. Protontricks might not have access to the directory.
Resolving PFX path...

Copying FF7 directory...
Done!

Setting up 7th Heaven...
Done!

Copying ff7.exe...
Done!

Altering Steam 7th Heaven shortcut for all Steam accounts...
Done!

Copying robocopy.bat...
Done!

Copying timeout.exe...
Done!

Copying saves...
cp: cannot stat '*.ff7': No such file or directory
Done!

Removing & installing dinput...

protontricks (WARNING): Protontricks does not appear to have access to the following directories:
 /run/media/mmcblk0p1

To fix this problem, grant access to the required directories by copying the following command and running it in a terminal:

flatpak override --user --filesystem=/run/media/mmcblk0p1 com.github.Matoking.protontricks

You will need to restart Protontricks for the settings to take effect.
protontricks (WARNING): Steam library folder /run/media/mmcblk0p1 not found. Protontricks might not have access to the directory.
steam-runtime-launcher-service[123]: W: The --socket option is deprecated. Prefer to use --session or --bus-name.
Using winetricks 20230212 (protontricks) - sha256sum: 033b8483b0317b58adac2a17333b7d14939b41d237c92d129f069362ef087e9e with wine-7.0 (Staging) and WINEARCH=win64
                                                   Executing w_do_call dinput
                                                                             Executing load_dinput
                                                                                                   grep: warning: stray \ before /
                    Executing cabextract -q -d /home/deck/.local/share/Steam/steamapps/compatdata/2348544883/pfx/dosdevices/c:/windows/temp -L -F dxnt.cab /home/deck/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9/directx_feb2010_redist.exe
                                        /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
Executing cabextract -q -d /home/deck/.local/share/Steam/steamapps/compatdata/2348544883/pfx/dosdevices/c:/windows/syswow64 -L -F dinput.dll /home/deck/.local/share/Steam/steamapps/compatdata/2348544883/pfx/dosdevices/c:/windows/temp/dxnt.cab
                      /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
/home/deck/.local/share/Steam/steamapps/compatdata/2348544883/pfx/dosdevices/c:/windows/temp/dxnt.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: dinput
                                                Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/GE-Proton7-54/bin/wine C:\windows\syswow64\regedit.exe C:\windows\Temp\override-dll.reg
    /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wine: using kernel write watches (experimental).
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/GE-Proton7-54/bin/wine64 C:\windows\regedit.exe C:\windows\Temp\override-dll.reg
                                                           /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wine: using kernel write watches (experimental).
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/GE-Proton7-54/bin/wine C:\windows\syswow64\regsvr32.exe dinput
                                         /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wine: using kernel write watches (experimental).
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
regsvr32: Successfully registered DLL 'dinput'

**Comment by dotaxis** [comment]
Is your copy of FF7 legitimate? It seems it's crashing on the anti-piracy check.

**Comment by DanBaigo** [comment]
That's strange. Yes is a legitimate copy. Just using the steam version.
![PXL_20230530_204705964](https://github.com/dotaxis/7H-SteamDeck-Fix/assets/112517583/474f5390-729e-4c51-95a3-53b8c0934e0c)

**Comment by dotaxis** [comment]
Can you uninstall FF7 and then make sure to delete the entire folder under steamapps/common before reinstalling?

I'm trying to get 7th Heaven devs to help me diagnose this issue but it may take some time. I still can't replicate it on my machine.

**Comment by DanBaigo** [comment]
I will go and try that now

**Comment by DanBaigo** [comment]
That sorted it! Deleted the FF7 Folder this time which I hadn't done before - had only uninstalled. Along with the 7th Heaven folder I'd been deleting that after each install. I must have put something in there it didn't like. Could it be something to do with symbolic linking maybe? I was trying to follow the other guide before stumbling on to your installer, so I'm not sure if some wires got crossed.

Could be worth a few one liners saying something like;
Before following this guide delete FF7 install folder here (or SD card link) - /home/deck/.local/share/Steam/steamapps/common/FINAL FANTASY VII/
Fresh reinstall, etc

Thanks so much for nudging me along with this its greatly appreciated. I was about to start remote playing via the PC and giving up. There are a few people on the Youtube comments also having this issue but there didn't seem to be a cut and shut solution, having come from another guide there must be some hangovers.

**Comment by bosam** [comment]
That's great news, you guys resolved this!
I'd suspect the other guides to introduce a crack to run FF7 without CD checks. That's what tools like Bottles or Lutris do when setting up install scripts.

**Comment by DanBaigo** [comment]
This makes sense!

**Comment by dotaxis** [comment]
I'm so glad that worked! There was a roadblock with a broken symlink that happened to people using the old Bottles setup, but that guide has been outdated for so long we haven't run into anyone with the issue.

What would happen is a symlink pointing to the parent directory would end up in the FF7 folder, which resulted in an infinite loop. I didn't suspect that could be an issue still, but I will remember it for future reference.

To anyone else having this issue, uninstall FF7 and then delete the entire Final Fantasy 7 folder under `steamapps/common/`, then reinstall FF7 and continue the rest of the process naturally.
